# Generated by Django 2.1.3 on 2018-11-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
    ]
